# Gradle settings
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Project settings
group=com.ewyboy.worldstripper

# Mod settings
mod_version=5.0.0
mod_id=worldstripper
mod_name=WorldStripper
mod_display_name=World Stripper
mod_authors=Ewy
mod_description=Strip the world of all its blocks
mod_license=MIT
mod_page_url=https://www.curseforge.com/minecraft/mc-mods/world-stripper
mod_issues_url=https://github.com/EwyBoy/World-Stripper/issues
mod_git_url=https://github.com/EwyBoy/World-Stripper
mod_curseforge_id=250603
mod_modrinth_id=world-stripper

# Common
minecraft_version=1.21
minecraft_version_range=[1.21,)

# Forge settings
forge_version=51.0.29
forge_version_range=[51.0.0,)
forge_loader_version_range=[51,)

# Neoforge settings
neoforge_version=21.0.146
neoforge_version_range=[21,)
neoforge_loader_version_range=[1,)

# Fabric settings
fabric_version=0.100.8+1.21
fabric_loader_version=0.15.11

# Dependencies