modLoader="javafml"
loaderVersion="[32,)"
license="MIT"
issueTrackerURL="https://github.com/EwyBoy/World-Stripper"
# displayURL="https://minecraft.curseforge.com/projects/world-stripper/"
logoFile="offending_image.png"
credits="Author: EwyBoy, based on strippermod_420 by Moze_Intel for 1.7.2"
authors="EwyBoy"

[[mods]]
modId="worldstripper"
version="${file.jarVersion}"
displayName="World Stripper"
# displayURL="https://www.curseforge.com/minecraft/mc-mods/world-stripper"
description="World Stripper is a lightweight modder / mapmaker tool that strips away the world to view underground world gen and do other world editing."

[[dependencies.worldstripper]]
modId="minecraft"
mandatory=true
versionRange="[1.16.+,)"
ordering="NONE"
side="BOTH"