modLoader="javafml"
loaderVersion="[2,)"
license="MIT"
issueTrackerURL="https://github.com/EwyBoy/AuctionHouse/issues"

[[mods]]
modId="worldstripper"
version="5.0.0"
displayName="World Stripper"
displayURL="https://github.com/EwyBoy/AuctionHouse"
authors="Ewy"
description="wow!"

[[dependencies.worldstripper]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.worldstripper]]
modId="minecraft"
type="required"
reason="You need Minecraft to play this mod"
versionRange="[1.21,)"
ordering="NONE"
side="BOTH"